Cleanup for release
pcdshub/las-dispersion-scan pull request #31
Opened 2024-09-13 17:26 UTC by slactjohnson

## Description
This PR adds a loader class that we've been using for the OPCPA systems for a while, as well as launcher scripts for various deployments that currently or previously existed. 

## Motivation and Context
This package has lived in a dev state for quite a while. Ken and I were working on this fairly actively ~Summer/Fall 2023. We got it into a mostly working state and the laser group was able to do what they needed with it. Then Ken left and I kind of forgot about this because no one was asking me questions. 

Recently qRIXS asked for two instances of the dispersion scanning application. After looking at the code I realized what a poor state we left it in. This PR aims to merge the updates we made and finally make a production release, cleaning up my mess. 

## How Has This Been Tested?
Tested pretty extensively by Mat Britton in IP1, and a little bit in XCS. RIX is testing this today (hopefully). 

## Where Has This Been Documented?
This PR.

2024-09-13 17:26 UTC, slactjohnson commented
Waiting for confirmation on qRIXS configurations before making ready for review.

2025-04-22 22:07 UTC, slactjohnson commented
This is really old, and the laser team has been running this exact code out of my dev area for a while. I'm just going to approve and merge, because this is blocking some new work from Adam.

2025-04-22 22:09 UTC, slactjohnson commented
Nevermind, I can't approve my own PR. :)

2025-04-22 22:10 UTC, tangkong commented
Checks and balances hah!  Mind merging in the changes from master?

2025-04-22 22:22 UTC, slactjohnson commented
@tangkong Sure, I'll update the branch. Do we prefer a merge commit or rebase?

2025-04-22 22:34 UTC, tangkong commented
Whichever you prefer, I prefer rebase personally but often merge commit is easier (a simple button click from github)

2025-04-22 22:37 UTC, tangkong approved these changes, later dismissed
This looks good to me on the whole, particularly if it's been running on prod for a while. 

A few nits, but otherwise I think it's good to get this in

2025-04-22 22:37 UTC, tangkong commented on run.sh
> +export PYTHONPATH=/cds/home/t/tjohnson/trunk/hutch-python/forks/pcdsdevices:$PYTHONPATH
Is there no deployment area for this in pyps or similar?  Having this run out of your personal space is a scary thing

2025-04-22 22:37 UTC, tangkong commented on las_dispersion_scan/loaders/qmini_and_opcpa_compressor.py
> +        return "mm"
Should this reflect the chosen motor units from the environment variable?

2025-04-22 22:39 UTC, slactjohnson commented on run.sh
> +export PYTHONPATH=/cds/home/t/tjohnson/trunk/hutch-python/forks/pcdsdevices:$PYTHONPATH
We will make one. I made a ticket to take care of this a while ago, but have been otherwise engaged: https://jira.slac.stanford.edu/browse/ECS-6490

Adam is going to make a small update to the code, so I think that he will be helping make a release or two, helping clean this up.

2025-04-22 22:42 UTC, tangkong commented
I do think this is worth adding tests to, but for the time being I bet if you added a single test to the suite, we'd get green ✅ s

2025-04-22 22:42 UTC, slactjohnson commented on las_dispersion_scan/loaders/qmini_and_opcpa_compressor.py
> +        return "mm"
That's a good point. Let me make an issue for that.

2025-04-22 22:44 UTC, tangkong commented
Actually, I'll just update pre-commit and add a dummy test to your branch myself

2025-04-22 22:44 UTC, slactjohnson commented on run.sh
> +export PYTHONPATH=/cds/home/t/tjohnson/trunk/hutch-python/forks/pcdsdevices:$PYTHONPATH
Ah I misread this comment. Yes, this is something I should check on. I forgot about this.

2025-04-22 22:53 UTC, tangkong commented
Ok I'll leave the other packaging/cleanup for a different PR.  There's a few more things to do than I thought, and I keep making typos 😆

2025-04-24 20:01 UTC, slactjohnson commented
This has all the changes I expect now. Waiting on testing from laser team later today.

2025-04-28 23:46 UTC, aberges-SLAC commented
@slactjohnson 

Do we consider this ready for merging, given the news from IP2's success?

2025-04-28 23:58 UTC, slactjohnson commented
@aberges-SLAC I was hoping to hear from at least one more deployment, like IP1. Are you aware of any news?

2025-04-29 00:04 UTC, aberges-SLAC commented
@slactjohnson We'll be out a few days then, as IP1 is in no-touch mode until tomorrow at least. No Class IV until Wednesday at best to test on IP1

2025-05-07 02:47 UTC, christina-pino requested changes
Looks good to me, though I am curious as to why the pip checks failed. Is it okay if the pull request fails through GitHub?

2025-05-07 03:08 UTC, tangkong commented
That's unrelated to this PR.  The packaging on this repo is a bit old, so the shared ci jobs aren't gathering the test dependencies properly.  The conda tests should be sufficient in the meantime

Though there are actually no tests here, so it's sort of a moot point 😆

2025-05-07 14:24 UTC, slactjohnson commented
I think this has been tested enough by Mat that it's ready for final review.

2025-05-12 18:47 UTC, aberges-SLAC commented on las_dispersion_scan/loaders/qmini_and_opcpa_compressor.py
> +            # TODO: instantiation order means this has to be available before the components
I have questions about this, but it's best to tackle that in a different branch I suppose.

Overall the changes look sensible to me

2025-05-12 18:47 UTC, aberges-SLAC commented on las_dispersion_scan/loaders/qmini_and_opcpa_compressor.py
> +qmini_prefix = os.environ.get("QMINI_PREFIX", "LAS:LLN:QMINI:01")
Why do we do this, exactly?

Is there a benefit to setting these globals and handling it in the wrapper shell script instead of just treating them like `__init__` parameters for the class?

2025-05-12 18:49 UTC, slactjohnson commented on las_dispersion_scan/loaders/qmini_and_opcpa_compressor.py
> +qmini_prefix = os.environ.get("QMINI_PREFIX", "LAS:LLN:QMINI:01")
This is something Ken did, and I have perpetuated. I don't know his original reason for doing so.

2025-05-12 18:50 UTC, aberges-SLAC commented on las_dispersion_scan/loaders/qmini_and_opcpa_compressor.py
> +    @scales.setter
When are we typically using upstream vs downstream scaling on the motor? Doesn't seem like we'd need to, since they're always bundled elliptecs of the same variety

2025-05-12 20:07 UTC, slactjohnson commented on las_dispersion_scan/loaders/qmini_and_opcpa_compressor.py
> +    @scales.setter
I think the idea here was that you could reverse direction with this factor, and make adjustments for non-ideal geometry. The two motor situation is a bit more complicated because you're creating a single pseudo motor out of two motors, so you need to be able to tweak things more than in the single motor case.

2025-05-12 20:53 UTC, tangkong commented on las_dispersion_scan/loaders/qmini_and_opcpa_compressor.py
> +qmini_prefix = os.environ.get("QMINI_PREFIX", "LAS:LLN:QMINI:01")
I think this makes sense if we're setting these values from a bash script and don't want to build a while cli frontend for passing this information to python-land.

It's maybe a little more opaque from the python endpoint, but it does make the bash scripts easier to read (sometimes having huge cli arg lists is annoying)

(trying to put myself in the shoes of Ken back in the day)

2025-05-12 21:04 UTC, tangkong approved these changes
I think this clean enough to move forward with, particularly if testing has been smooth.  There are a few rough edges but I think I need to grok the rest of this package before I object too loudly

2025-05-12 21:04 UTC, tangkong commented on las_dispersion_scan/loaders/qmini_and_opcpa_compressor.py
> +        return "mm"
This still hasn't been addressed, if you were planning on it

2025-05-12 21:31 UTC, slactjohnson commented on las_dispersion_scan/loaders/qmini_and_opcpa_compressor.py
> +        return "mm"
I don't plan on addressing it right now. I will make an issue once this PR has been merged so that there is something for me to reference.

2025-06-10 20:24 UTC, slactjohnson commented
@aberges-SLAC Any concern merging here? 

@christina-pino Yes, in this case it's fine. The CI/CD needs a little work in this package still.

2025-06-10 21:02 UTC, aberges-SLAC commented
Nope! The CI is a longstanding issue I've seen from other PRs. Mat tested the changes here so it is fine in my eyes.

I can clean up the `egu` thing in a future commit as I work through all the outstanding issues

2025-06-11 14:06 UTC, slactjohnson commented
@christina-pino Looking for confirmation that you're fine with this; your review requested changes so I can't merge. 
If I don't hear any complaints by the end of the day I'll dismiss the review and merge.

2025-06-12 00:52 UTC, christina-pino approved these changes
gtg

2025-06-12 13:39 UTC, slactjohnson commented
Hmm seems I am still not able to merge due to the failing tests

2025-06-12 16:26 UTC, merged

2025-06-12 16:26 UTC, tangkong commented
I'll disable the tests here, this is my fault anyway I think